import type {
  CreateProjectResponse,
  GetProjectResponse,
  Project,
  ProjectFileNode,
  ProjectObjectKind,
  ProjectObjectNode
} from "@bg-maker/shared";
import { expect, type Locator, type Page } from "@playwright/test";
import { ProjectWorkspacePage } from "../game-objects/pages/project-workspace-page";

export async function createProjectWithFileTree(
  page: Page,
  name: string,
  fileTree: ProjectFileNode[]
) {
  const createResponse = await page.request.post("/api/projects", {
    data: { name, description: "Generated by reboot editor e2e" }
  });

  expect(createResponse.ok()).toBe(true);

  const { project } = (await createResponse.json()) as CreateProjectResponse;
  const updateResponse = await page.request.patch(`/api/projects/${project.id}/file-tree`, {
    data: { fileTree: withRequiredRootFolders(fileTree) }
  });

  expect(updateResponse.ok()).toBe(true);

  return getProject(page, project.id);
}

export async function openProject(page: Page, project: Project) {
  await page.goto(`/projects/${project.id}`);
  await new ProjectWorkspacePage(page).expectProjectOpen(project.name);
}

export async function openFileNode(page: Page, name: string) {
  await getFileTree(page)
    .getByRole("button", { name: new RegExp(`^${escapeRegExp(name)}$`) })
    .click();
}

export async function createObjectFileFromFileTree(
  page: Page,
  {
    name,
    parentName,
    rootType
  }: {
    name: string;
    parentName: string;
    rootType: "Bag" | "Card" | "Group" | "Label" | "Meeple" | "Shape" | "Token";
  }
) {
  await getFileTree(page).getByRole("button", { name: new RegExp(`^${escapeRegExp(parentName)}`) }).click({
    button: "right"
  });
  const menu = page.getByRole("menu", { name: "File tree context menu" });

  await menu.getByRole("menuitem", { name: "Create" }).hover();
  await menu.getByRole("menuitem", { name: "Object" }).click();

  const dialog = page.getByRole("dialog", { name: "New object" });
  await dialog.getByRole("radio", { name: rootType, exact: true }).click();
  await dialog.getByLabel("Name").fill(name);
  await dialog.getByRole("button", { name: "Create", exact: true }).click();

  await openFileNode(page, name);
}

export async function dragTreeItem(
  page: Page,
  sourceName: string,
  targetName: string,
  horizontalOffset: number
) {
  const fileTree = getFileTree(page);
  const source = fileTree.getByRole("button", { name: sourceName, exact: true });
  const target = fileTree.getByRole("button", { name: targetName, exact: true });
  const sourceBox = await source.boundingBox();
  const targetBox = await target.boundingBox();

  if (!sourceBox || !targetBox) {
    throw new Error(`Could not drag ${sourceName} to ${targetName}`);
  }

  const sourceX = sourceBox.x + Math.min(20, sourceBox.width / 2);
  const sourceY = sourceBox.y + sourceBox.height / 2;
  const targetX = targetBox.x + Math.min(20, targetBox.width / 2) + horizontalOffset;
  const targetY = targetBox.y + targetBox.height / 2;

  await page.mouse.move(sourceX, sourceY);
  await page.mouse.down();
  await page.mouse.move(sourceX + horizontalOffset, sourceY, { steps: 6 });
  await page.mouse.move(targetX, targetY, { steps: 12 });
  await page.mouse.up();
}

export async function dragBy(locator: Locator, deltaX: number, deltaY: number) {
  const box = await locator.boundingBox();

  if (!box) {
    throw new Error("Could not drag object because its frame was not visible");
  }

  const startX = box.x + box.width / 2;
  const startY = box.y + box.height / 2;

  await locator.page().mouse.move(startX, startY);
  await locator.page().mouse.down();
  await locator.page().mouse.move(startX + deltaX, startY + deltaY, { steps: 12 });
  await locator.page().mouse.up();
}

export async function getProject(page: Page, projectId: string) {
  const response = await page.request.get(`/api/projects/${projectId}`);
  const { project } = (await response.json()) as GetProjectResponse;

  return project;
}

export async function getRootObject(page: Page, projectId: string, fileName: string) {
  return getRootObjectFromProject(await getProject(page, projectId), fileName);
}

export function getRootObjectFromProject(project: Project, fileName: string) {
  return findFileNode(project.fileTree, (node) => node.name === fileName)?.objectTree?.[0];
}

export async function getRootRectTransform(page: Page, projectId: string, fileName: string) {
  return getRootObject(page, projectId, fileName).then(
    (object) => object?.components?.rectTransform
  );
}

export async function getRootImageAssetId(page: Page, projectId: string, fileName: string) {
  return getRootObject(page, projectId, fileName).then(
    (object) => object?.components?.image?.assetId ?? ""
  );
}

export async function getNodeParentId(page: Page, projectId: string, nodeId: string) {
  const project = await getProject(page, projectId);

  return findNodeParentId(project.fileTree, nodeId);
}

export function getProjectIdFromUrl(page: Page) {
  const projectId = new URL(page.url()).pathname.split("/").at(-1);

  if (!projectId) {
    throw new Error("Project id was not found in the current URL");
  }

  return projectId;
}

export function objectsFolder(children: ProjectFileNode[] = []): ProjectFileNode {
  return {
    id: "objects",
    name: "Objects",
    type: "folder",
    children
  };
}

export function objectFile(
  id: string,
  name: string,
  rootObject: ProjectObjectNode
): ProjectFileNode {
  return {
    id,
    kind: "object",
    name,
    objectTree: [rootObject],
    type: "file"
  };
}

export function objectNode(
  id: string,
  name: string,
  kind: ProjectObjectKind,
  components?: ProjectObjectNode["components"],
  children: ProjectObjectNode[] = []
): ProjectObjectNode {
  return {
    id,
    name,
    kind,
    visible: true,
    components,
    children
  };
}

export function findFileNode(
  fileTree: ProjectFileNode[],
  predicate: (node: ProjectFileNode) => boolean
): ProjectFileNode | undefined {
  for (const node of fileTree) {
    if (predicate(node)) {
      return node;
    }

    if (node.type === "folder") {
      const childNode = findFileNode(node.children ?? [], predicate);

      if (childNode) {
        return childNode;
      }
    }
  }

  return undefined;
}

export function findImageAssetFileName(project: Project) {
  return findFileNode(project.fileTree, (node) => node.kind === "image" && Boolean(node.imageAsset))
    ?.name;
}

export const pngPixelBuffer = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=",
  "base64"
);

function getFileTree(page: Page) {
  return page.getByRole("complementary").first();
}

function withRequiredRootFolders(fileTree: ProjectFileNode[]): ProjectFileNode[] {
  const rootIds = new Set(fileTree.map((node) => node.id));

  return [
    rootIds.has("table-setups")
      ? null
      : {
          id: "table-setups",
          name: "Table setups",
          type: "folder" as const,
          children: []
        },
    ...fileTree,
    rootIds.has("assets")
      ? null
      : {
          id: "assets",
          name: "Assets",
          type: "folder" as const,
          children: []
        }
  ].filter((node): node is ProjectFileNode => Boolean(node));
}

function findNodeParentId(
  fileTree: ProjectFileNode[],
  nodeId: string,
  parentId: string | null = null
): string | null | undefined {
  for (const node of fileTree) {
    if (node.id === nodeId) {
      return parentId;
    }

    if (node.type === "folder") {
      const childParentId = findNodeParentId(node.children ?? [], nodeId, node.id);

      if (childParentId !== undefined) {
        return childParentId;
      }
    }
  }

  return undefined;
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
